### PR TITLE
Several issues fixed.

### PR DESCRIPTION
**Pull request by whiggs**
These changes fix several issues.  Two additional variables can be set in the vagrant file (primary_dns and secondary_dns) which will statically set the primary and secondary dns servers on the vm's nic, which, if configured correctly, can allow the vm to successfully communicate with the domain controller if the vm was unable to without setting the nic's DNS settings.  Also fixed an issue in regards to renaming the machine while domain-joining it.  The only thing I was unable to get perfect is that when destroying the vm, after the vm is removed from the domain, it has to restart prior to actually destroying the vm, but the plugin does work now.

### CODE REVIEW

**Comment by whiggs** [comment]
Despite what the check says, broken as it is, modified version of the vagrant-windows-domain plugin is perfectly functional and fixes a lot of issues with the plugin.  I highly recommend you commit the change.

**Comment by chrisgannon6** [comment]
I'd like to test this. 

@whiggs which version of Vagrant were you using when you tested this? And which provider (VMWare Workstation?)

**Comment by whiggs** [comment]
@chrisgannon6 Please feel free to test all you like.  When I was testing it,. I used the most up to date vagrant, version 2.1.5 (why would you use a not up-to-date version), and I used the vagrantfile provided in the development folder in the repository (which uses the virtualbox provider).  I hope this answered your questions.

**Comment by whiggs** [comment]
Any update on merging this?

**Comment by whiggs** [comment]
I have modified the plugin again and improved its performance.  I felt the plugin forced the vm being provisioned to restart unnecessarily several times, so I have removed the unnecessary restarts from the plugin to reduce the amount of time it takes to provision the vm.  I removed one of the two restarts when the vm is joined to the domain and I have removed all of the restarts performed after the vm is dis-joined from the domain (since this usually indicates the vm is being destroyed, the vm does not need to be restarted, it can just be destroyed).  It now works perfectly (at least I think it does).  Please feel free to test it yourselves, but please merge the changes and update the gem so that the plugin is readily available.  If you find a problem with it, then let me know so I can fix it, but if not, merge it.

**Comment by mefellows** [comment]
Thanks @whiggs, these all sound like great changes.

I'm hesitant to merge anything with a broken build - i'm very much out of touch with Vagrant plugin development, but the build seems to be stuck in the early stages - it looks like there is a configuration issue removing/installing bundler.

Are you able to look at this before I merge it in (which I very much want to do)?

**Comment by whiggs** [comment]
@mefellows I am pretty sure my modifications are not the reason behind the build failing, but rather, the .travis.yml configuration file.  Looking at the build errors, the build fails when running "gem uninstall bundler --all --executables" because (according to travis) "gem "bundler" cannot be uninstalled because it is a default gem."  I can attempt to modify the .travis.yml file for you to make it work, but that kind of defeats the purpose of having the .travis.yml file in the first place right?  In the end, its up to you.  You want to fix it, or do you want me to?

**Comment by whiggs** [comment]
Ok.  Took quite a few tries, but the travis build configuration has been modified so that it passes the check,  Can you merge it now?

**Comment by whiggs** [comment]
There we go.  Now it is really ready.

**Pull request merged**
